# Generated by Django 4.2.17 on 2025-12-24 12:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(help_text="Google'da görünecek başlık (60 karakter önerilir)", max_length=60, verbose_name='Meta Başlık')),
                ('meta_description', models.CharField(help_text="Google'da görünecek açıklama (160 karakter önerilir)", max_length=160, validators=[django.core.validators.MinLengthValidator(50)], verbose_name='Meta Açıklama')),
                ('meta_keywords', models.CharField(blank=True, help_text='Virgülle ayrılmış anahtar kelimeler', max_length=255, verbose_name='Anahtar Kelimeler')),
                ('og_title', models.CharField(blank=True, help_text='Sosyal medyada paylaşıldığında görünecek başlık', max_length=95, verbose_name='Open Graph Başlık')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='Open Graph Açıklama')),
                ('og_image', models.ImageField(blank=True, help_text='1200x630px önerilir', null=True, upload_to='seo/og_images/', verbose_name='Open Graph Görseli')),
                ('twitter_card_type', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', max_length=50, verbose_name='Twitter Card Tipi')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Kart görünümlerinde gösterilecek kısa özet', max_length=300, verbose_name='Özet')),
                ('thumbnail', models.ImageField(help_text='Ana görsel - 1200x800px önerilir', upload_to='articles/thumbnails/%Y/%m/', verbose_name='Kapak Görseli')),
                ('thumbnail_alt', models.CharField(help_text='SEO için görsel açıklaması', max_length=200, verbose_name='Görsel Alt Metni')),
                ('author_name', models.CharField(max_length=100, verbose_name='Yazar Adı')),
                ('author_bio', models.TextField(blank=True, verbose_name='Yazar Biyografisi')),
                ('reading_time', models.IntegerField(default=5, help_text='Tahmini okuma süresi', verbose_name='Okuma Süresi (dakika)')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_published', models.BooleanField(default=False, verbose_name='Yayında')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('noindex', models.BooleanField(default=False, help_text='Arama motorlarından gizle', verbose_name='Noindex')),
                ('view_count', models.IntegerField(default=0, verbose_name='Görüntülenme')),
            ],
            options={
                'verbose_name': 'Makale',
                'verbose_name_plural': 'Makaleler',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.CharField(default='📝', max_length=10, verbose_name='Emoji İkon')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(help_text="Google'da görünecek başlık (60 karakter önerilir)", max_length=60, verbose_name='Meta Başlık')),
                ('meta_description', models.CharField(help_text="Google'da görünecek açıklama (160 karakter önerilir)", max_length=160, validators=[django.core.validators.MinLengthValidator(50)], verbose_name='Meta Açıklama')),
                ('meta_keywords', models.CharField(blank=True, help_text='Virgülle ayrılmış anahtar kelimeler', max_length=255, verbose_name='Anahtar Kelimeler')),
                ('og_title', models.CharField(blank=True, help_text='Sosyal medyada paylaşıldığında görünecek başlık', max_length=95, verbose_name='Open Graph Başlık')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='Open Graph Açıklama')),
                ('og_image', models.ImageField(blank=True, help_text='1200x630px önerilir', null=True, upload_to='seo/og_images/', verbose_name='Open Graph Görseli')),
                ('twitter_card_type', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', max_length=50, verbose_name='Twitter Card Tipi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('structured_data', models.JSONField(blank=True, help_text='Organization, WebSite vb. schema.org verileri', null=True, verbose_name='Yapılandırılmış Veri (JSON-LD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anasayfa SEO',
                'verbose_name_plural': 'Anasayfa SEO',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Bülten Abonesi',
                'verbose_name_plural': 'Bülten Aboneleri',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('paragraph_type', models.CharField(choices=[('text', 'Normal Paragraf'), ('heading', 'Alt Başlık'), ('quote', 'Alıntı'), ('code', 'Kod Bloğu')], default='text', max_length=20, verbose_name='Paragraf Tipi')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('heading_text', models.CharField(blank=True, help_text="Sadece 'Alt Başlık' tipi için", max_length=200, verbose_name='Alt Başlık')),
                ('code_language', models.CharField(blank=True, help_text='Örn: python, javascript, html', max_length=50, verbose_name='Kod Dili')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='blog.article', verbose_name='Makale')),
            ],
            options={
                'verbose_name': 'Makale Paragrafı',
                'verbose_name_plural': 'Makale Paragrafları',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/content_images/%Y/%m/', verbose_name='Görsel')),
                ('alt_text', models.CharField(help_text='SEO için görsel açıklaması', max_length=200, verbose_name='Alt Metin')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Görsel Başlığı')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('after_paragraph', models.ForeignKey(blank=True, help_text='Boş bırakılırsa sırasına göre gösterilir', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following_images', to='blog.articleparagraph', verbose_name='Hangi Paragraftan Sonra')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.article', verbose_name='Makale')),
            ],
            options={
                'verbose_name': 'Makale Görseli',
                'verbose_name_plural': 'Makale Görselleri',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.category', verbose_name='Kategori'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_date', 'is_published'], name='blog_articl_publish_088061_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='blog_articl_slug_cc8df7_idx'),
        ),
    ]
