# Generated by Django 4.2.17 on 2025-12-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('message_tr', models.TextField(default='Bu web sitesi, deneyiminizi geliştirmek için çerezler kullanmaktadır.', verbose_name='Mesaj (TR)')),
                ('message_en', models.TextField(default='This website uses cookies to improve your experience.', verbose_name='Mesaj (EN)')),
                ('button_text_tr', models.CharField(default='Anladım', max_length=50, verbose_name='Buton Metni (TR)')),
                ('button_text_en', models.CharField(default='I Understand', max_length=50, verbose_name='Buton Metni (EN)')),
                ('policy_link_text_tr', models.CharField(default='Çerez Politikası', max_length=50, verbose_name='Politika Linki (TR)')),
                ('policy_link_text_en', models.CharField(default='Cookie Policy', max_length=50, verbose_name='Politika Linki (EN)')),
            ],
            options={
                'verbose_name': 'Çerez Onayı Ayarları',
                'verbose_name_plural': 'Çerez Onayı Ayarları',
            },
        ),
        migrations.CreateModel(
            name='CookiePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(default='Çerez Politikası', max_length=200, verbose_name='Başlık (TR)')),
                ('title_en', models.CharField(default='Cookie Policy', max_length=200, verbose_name='Başlık (EN)')),
                ('content_tr', models.TextField(verbose_name='İçerik (TR)')),
                ('content_en', models.TextField(verbose_name='İçerik (EN)')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='Son Güncelleme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('meta_description_tr', models.CharField(blank=True, max_length=160, verbose_name='Meta Açıklama (TR)')),
                ('meta_description_en', models.CharField(blank=True, max_length=160, verbose_name='Meta Açıklama (EN)')),
            ],
            options={
                'verbose_name': 'Çerez Politikası',
                'verbose_name_plural': 'Çerez Politikası',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt_en',
            field=models.TextField(blank=True, help_text='İngilizce kısa özet', max_length=300, verbose_name='Özet (EN)'),
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English'), ('both', 'İki Dilde')], default='both', max_length=10, verbose_name='Dil'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Açıklama (EN)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Anahtar Kelimeler (EN)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='Meta Başlık (EN)'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Başlık (EN)'),
        ),
        migrations.AddField(
            model_name='articleparagraph',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='İçerik (EN)'),
        ),
        migrations.AddField(
            model_name='articleparagraph',
            name='heading_text_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt Başlık (EN)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(help_text='Kart görünümlerinde gösterilecek kısa özet', max_length=300, verbose_name='Özet (TR)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık (TR)'),
        ),
        migrations.AlterField(
            model_name='articleparagraph',
            name='content',
            field=models.TextField(verbose_name='İçerik (TR)'),
        ),
        migrations.AlterField(
            model_name='articleparagraph',
            name='heading_text',
            field=models.CharField(blank=True, help_text="Sadece 'Alt Başlık' tipi için", max_length=200, verbose_name='Alt Başlık (TR)'),
        ),
    ]
