# Generated by Django 4.2.17 on 2026-01-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cookieconsent_cookiepolicy_article_excerpt_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleparagraph',
            name='content',
            field=models.TextField(blank=True, verbose_name='İçerik (TR)'),
        ),
        migrations.AlterField(
            model_name='articleparagraph',
            name='paragraph_type',
            field=models.CharField(blank=True, choices=[('text', 'Normal Paragraf'), ('heading', 'Alt Başlık'), ('quote', 'Alıntı'), ('code', 'Kod Bloğu')], default='text', max_length=20, null=True, verbose_name='Paragraf Tipi'),
        ),
    ]
